FROM php:7.0-fpm
RUN docker-php-ext-install mysqli pdo pdo_mysql
RUN docker-php-ext-enable mysqli




#COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
#COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
